apiVersion: v1
kind: Namespace
metadata:
  name: spring-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-crud
  namespace: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-crud
  template:
    metadata:
      labels:
        app: spring-boot-crud
    spec:
      initContainers:
        - name: otel-agent
          image: curlimages/curl:8.10.1
          command:
            - sh
            - -c
            - |
              curl -L \
                -o /otel/opentelemetry-javaagent.jar \
                https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar
          volumeMounts:
            - name: otel-agent
              mountPath: /otel

      containers:
        - name: spring-boot-crud
          image: aniket1992/spring-boot-crud:1.8
          imagePullPolicy: Always

          ports:
            - containerPort: 8081

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres.app-data.svc.cluster.local:5432/appdb

            - name: SPRING_DATASOURCE_USERNAME
              value: appuser

            - name: SPRING_DATASOURCE_PASSWORD
              value: apppassword

            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/otel/opentelemetry-javaagent.jar"

            - name: GO_PRODUCT_SERVICE_URL
              value: "http://go-rest-api.go-app.svc.cluster.local:8084"

            - name: NODE_TUTORIAL_SERVICE_URL
              value: "http://node-express-api.node-app.svc.cluster.local:9090"

            - name: OTEL_SERVICE_NAME
              value: spring-boot-crud

            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://o2c-openobserve-collector-gateway-collector.openobserve-collector.svc.cluster.local:4318

            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf

            - name: OTEL_TRACES_EXPORTER
              value: otlp

            - name: OTEL_METRICS_EXPORTER
              value: otlp

            - name: OTEL_LOGS_EXPORTER
              value: none

          volumeMounts:
            - name: otel-agent
              mountPath: /otel

      volumes:
        - name: otel-agent
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-crud
  namespace: spring-app
spec:
  selector:
    app: spring-boot-crud
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
